POST http://localhost:8080/api/users/signup HTTP/1.1
content-type: application/json

{
    "name": "test name",
    "email": "test@test.com",
    "password": "123123"
}

###

POST http://localhost:8080/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "123123"
}